### ISSUE TITLE
Code questions

### ISSUE THREAD

**Issue by Mleader2** [jcyk/seqgen#2]
question1:  ranker/data.py中的第67行 tgt = ListsToTensor([x[1] for x in data], vocab_src), 对tgt的序列号为什么使用src的vocab呢?
question2:文献1689页的第一段表明训练Skeleton-guided Response Generator时,对ground-truth response的若干随机操作得到Skeleton. 对应的代码是不是data.py(不是ranker文件夹中的)?  data.py是对ref_tgt进行随机操作的,ref_tgt不是检索得到的回复么?
谢谢指导!

**Comment by jcyk** [comment]
你好
1.  谢谢发现这个问题，因为我们的实验中vocab_src 和vocab_tgt 是相同的，参考preprocess_zh/segment.py 所以没受这个bug的影响
2. 是的 ref_tgt在testing时是检索的回复， 在training时是随机操作的结果。

**Comment by jcyk** [comment]
@Mleader2 今天会更新repo 添加一些说明，敬请期待。

**Comment by jcyk** [comment]
let me know if you have further questions.
