### ISSUE TITLE
Problems with data sets and loss functions

### ISSUE THREAD

**Issue by ZhengDanYang1** [jcyk/seqgen#3]
Hello, I have some problems when studying the code: 
1. The difference between the two data sets, when to use **train.txt** and when to use **train.retrieval. txt**.
2. There are two losses in masker_ranker.py. What is the function of baseline_mse loss?It doesn't seem to be reflected in your paper.

**Comment by jcyk** [comment]
train.txt is used for our models, while train.retrieval.txt is used for
other models that require retrieval results during training.

The baseline mse is used in our preliminary experiments. This loss term is
not used in our published version. Sorry for the confusion.

Best,
Deng
