### ISSUE TITLE
train.txt 与模型输入不匹配

### ISSUE THREAD

**Issue by wizare** [jcyk/seqgen#5]
根据readme里的说法，模型使用的是train.txt，而其他模型使用的是train.retrieval.txt。
但是train.txt 每一行是query-response的二元组，在你的代码中默认输入格式都是四元组，这导致不能载入train.txt里的数据。
请问应该怎么解决？

**Comment by jcyk** [comment]
这个代码为了方便就用了统一的格式，解决方案如下
query-response-query-response
即把query-response重复一遍
